### PR TITLE
press kit + dashboard

### PR DESCRIPTION
**Pull request by rolandpo**
replace press kit logos, #49
add dashboard link, #63

### CODE REVIEW

**Review by nickick — APPROVED** [review]
LGTM, thanks

**Comment by micahalcorn** [comment]
@rolandpo @nickick unless I'm mistaken, this only changes the assets that are exported and not the images displayed on the page.

Screen Shot 2022-11-23 at 11 46 15 AM

**Comment by rolandpo** [comment]
@micahalcorn ah I originally pulled those in from Figma, together with the background and all to pass to the card component. Would be possible to get the updated designs in that form as one image?

**Comment by matt-bullock** [comment]
@rolandpo @micahalcorn https://www.figma.com/file/bCp9T3weuhTACy5f6zyl2t/Origin-Story-System?node-id=1357%3A850&t=ZrUkS8XzSOEp1t68-1 this is the up to date version 

image


And here are all the logos/icons. The folders inside correspond to each download link. No need to have separate SVG and PNG downloads. Just allow the user to download all assets for whichever project they need. 

[Origin Dollar.zip](https://github.com/OriginProtocol/website-frontend/files/10079402/Origin.Dollar.zip)
[Origin Story.zip](https://github.com/OriginProtocol/website-frontend/files/10079403/Origin.Story.zip)
[Origin.zip](https://github.com/OriginProtocol/website-frontend/files/10079405/Origin.zip)

**Comment by rolandpo** [comment]
ah ok perfect

**Comment by rolandpo** [comment]
ready in #67

**Pull request merged**
